'use strict';function t(f,a,b,c){f.v.lc(f.Za,a,b,c,void 0)}function D(f,a,b,c){f.v.ra?t(f,a,b,c):f.v.jf()._OnMessageFromDOM({type:"event",component:f.Za,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function G(f,a,b){f.v.C(f.Za,a,b)}function H(f,a){for(const [b,c]of a)G(f,b,c)}function I(f){f.Pb||(f.v.Te(f.be),f.Pb=!0)}window.Da=class{constructor(f,a){this.v=f;this.Za=a;this.Pb=!1;this.be=()=>this.Ga()}dd(){}Ga(){}};function K(f){-1!==f.Ra&&(self.clearTimeout(f.Ra),f.Ra=-1)}
window.Ke=class{constructor(f,a){this.Lc=f;this.wg=a;this.Ra=-1;this.Qb=-Infinity;this.ce=()=>{this.Ra=-1;this.Qb=Date.now();this.eb=!0;this.Lc();this.eb=!1};this.Ld=this.eb=!1}c(){K(this);this.ce=this.Lc=null}};"use strict";function L(f,a){const b=a.elementId,c=f.hd(b,a);f.Y.set(b,c);a.isVisible||(c.style.display="none");c.addEventListener("focus",()=>{M(f,"elem-focused",b)});c.addEventListener("blur",()=>{M(f,"elem-blurred",b)});f.Kb&&document.body.appendChild(c)}
function N(f,a){G(f,"get-element",b=>{const c=f.Y.get(b.elementId);return a(c,b)})}function M(f,a,b,c){c||(c={});c.elementId=b;t(f,a,c)}
window.xe=class extends self.Da{constructor(f,a){super(f,a);this.Y=new Map;this.Kb=!0;H(this,[["create",b=>L(this,b)],["destroy",b=>{{b=b.elementId;const c=this.Y.get(b);this.Kb&&c.parentElement.removeChild(c);this.Y.delete(b)}}],["set-visible",b=>{this.Kb&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Kb){var c=this.Y.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=b.height+"px";b=b.fontSize;
null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{{const c=this.Y.get(b.elementId);this.rc(c,b)}}],["focus",b=>this.Gc(b)],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);N(this,b=>b)}hd(){throw Error("required override");}rc(){throw Error("required override");}Gc(f){var a=this.Y.get(f.elementId);f.focus?a.focus():a.blur()}};
"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(k,d){const h=document.createElement("script");h.async=!1;"module"===d&&(h.type="module");return k.Gg?new Promise(l=>{const n="c3_resolve_"+a;++a;self[n]=l;h.textContent=k.Jg+`\n\nself["${n}"]();`;document.head.appendChild(h)}):new Promise((l,n)=>{h.onload=l;h.onerror=n;h.src=k;document.head.appendChild(h)})}let c=!1,g=!1;function m(){if(!c){try{new Worker("blob://",{get type(){g=!0}})}catch(k){}c=!0}return g}
let p=new Audio;const v={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function A(k){k=await B(k);return(new TextDecoder("utf-8")).decode(k)}function B(k){return new Promise((d,
h)=>{const l=new FileReader;l.onload=n=>d(n.target.result);l.onerror=n=>h(n);l.readAsArrayBuffer(k)})}const w=[];let x=0;window.RealFile=window.File;const C=[],y=new Map,E=new Map;let F=0;const J=[];self.runOnStartup=function(k){if("function"!==typeof k)throw Error("runOnStartup called without a function");J.push(k)};const e=new Set(["cordova","playable-ad","instant-games"]);window.ua=class k{constructor(d){this.ra=d.Lg;this.pa=null;this.F="";this.Yb=d.Ig;this.da=d.fe;this.sb={};this.Ka=this.rb=null;
this.Nb=[];this.gb=this.K=this.Pa=null;this.Oa=-1;this.Bg=()=>this.If();this.Na=[];this.B=d.de;!this.ra||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&("module"!==this.da||m())||(this.ra=!1);e.has(this.B)&&this.ra&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this.ra=!1);this.Sb=this.ia=null;"html5"!==this.B&&"playable-ad"!==this.B||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");
this.C("runtime","cordova-fetch-local-file",h=>this.sf(h));this.C("runtime","create-job-worker",()=>this.tf());"cordova"===this.B?document.addEventListener("deviceready",()=>this.xd(d)):this.xd(d)}c(){this.sc();this.pa&&(this.pa=this.pa.onmessage=null);this.rb&&(this.rb.terminate(),this.rb=null);this.Ka&&(this.Ka.c(),this.Ka=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}nd(){return f&&"cordova"===this.B}kc(){return f&&e.has(this.B)||navigator.standalone}async xd(d){if("playable-ad"===
this.B){this.ia=self.c3_base64files;this.Sb={};await this.Ze();for(let l=0,n=d.Sa.length;l<n;++l){var h=d.Sa[l].toLowerCase();this.Sb.hasOwnProperty(h)?d.Sa[l]={Gg:!0,Jg:this.Sb[h]}:this.ia.hasOwnProperty(h)&&(d.Sa[l]=URL.createObjectURL(this.ia[h]))}}d.Cg?this.F=d.Cg:(h=location.origin,this.F=("null"===h?"file:///":h)+location.pathname,h=this.F.lastIndexOf("/"),-1!==h&&(this.F=this.F.substr(0,h+1)));d.Ng&&(this.sb=d.Ng);h=new MessageChannel;this.pa=h.port1;this.pa.onmessage=l=>this._OnMessageFromRuntime(l.data);
window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Ef(l));this.gb=new self.Ge(this);await O(this.gb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ra?await this.mf(d,h.port2):await this.lf(d,h.port2)}vc(d){d=this.sb.hasOwnProperty(d)?this.sb[d]:d.endsWith("/workermain.js")&&this.sb.hasOwnProperty("workermain.js")?this.sb["workermain.js"]:"playable-ad"===this.B&&this.ia.hasOwnProperty(d.toLowerCase())?
this.ia[d.toLowerCase()]:d;d instanceof Blob&&(d=URL.createObjectURL(d));return d}async cc(d,h,l){if(d.startsWith("blob:"))return new Worker(d,l);if(this.nd()&&"file:"===location.protocol)return d=await this.ub(this.Yb+d),new Worker(URL.createObjectURL(new Blob([d],{type:"application/javascript"})),l);d=new URL(d,h);if(location.origin!==d.origin){d=await fetch(d);if(!d.ok)throw Error("failed to fetch worker script");d=await d.blob();return new Worker(URL.createObjectURL(d),l)}return new Worker(d,
l)}xa(){return Math.max(window.innerWidth,1)}wa(){return Math.max(window.innerHeight,1)}wd(d){var h=this.gb;return{baseUrl:this.F,windowInnerWidth:this.xa(),windowInnerHeight:this.wa(),devicePixelRatio:window.devicePixelRatio,isFullscreen:k.jc(),projectData:d.Tg,scriptsType:d.fe,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Rg||"",exportType:d.de,isDebug:-1<self.location.search.indexOf("debug"),
ife:!!self.Sg,jobScheduler:{inputPort:h.Rc,outputPort:h.Yc,maxNumWorkers:h.yg},supportedAudioFormats:v,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Yb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Yb+"opus.wasm.wasm",isiOSCordova:this.nd(),isiOSWebView:this.kc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async mf(d,h){var l=this.vc(d.Mg);this.rb=await this.cc(l,this.F,{type:this.da,name:"Runtime"});this.K=document.createElement("canvas");this.K.style.display=
"none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);window.c3canvas=this.K;this.rb.postMessage(Object.assign(this.wd(d),{type:"init-runtime",isInWorker:!0,messagePort:h,canvas:l,workerDependencyScripts:d.cd||[],engineScripts:d.Sa,projectScripts:d.tb,mainProjectScript:d.ee,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[h,l,...P(this.gb)]);this.Nb=C.map(n=>new n(this));this.vd();self.c3_callFunction=(n,q)=>this.Pa.nf(n,q);"preview"===this.B&&(self.goToLastErrorScript=
()=>this.lc("runtime","go-to-last-error-script"))}async lf(d,h){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Nb=C.map(q=>new q(this));this.vd();var l=d.Sa.map(q=>"string"===typeof q?(new URL(q,this.F)).toString():q);Array.isArray(d.cd)&&l.unshift(...d.cd);l=await Promise.all(l.map(q=>this.zc(q,this.da)));await Promise.all(l.map(q=>b(q,this.da)));const n=self.C3_ProjectScriptsStatus;if("module"===this.da){l=d.ee;const q=
d.tb;for(let [u,r]of q)if(r||(r=u),u===l)try{r=await this.zc(r,this.da),await b(r,this.da),"preview"!==this.B||n[u]||this.Fd(u,"main script did not run to completion")}catch(z){this.Fd(u,z)}else if("scriptsInEvents.js"===u||u.endsWith("/scriptsInEvents.js"))r=await this.zc(r,this.da),await b(r,this.da)}else if(d.tb&&0<d.tb.length)try{if(await Promise.all(d.tb.map(q=>b(q[1],this.da))),Object.values(n).some(q=>!q)){self.setTimeout(()=>this.Gd(n),100);return}}catch(q){console.error("[Preview] Error loading project scripts: ",
q);self.setTimeout(()=>this.Gd(n),100);return}"preview"===this.B&&"object"!==typeof self.Og.Pg?(this.Xa(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(d=Object.assign(this.wd(d),{isInWorker:!1,messagePort:h,canvas:this.K,runOnStartupFunctions:J}),this.zd(),this.Ka=self.C3_CreateRuntime(d),await self.C3_InitRuntime(this.Ka,
d))}Gd(d){this.Xa();d=`Failed to load project script '${Object.entries(d).filter(h=>!h[1]).map(h=>h[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+d);alert(d)}Fd(d,h){this.Xa();console.error(`[Preview] Failed to load project main script (${d}): `,h);alert(`Failed to load project main script (${d}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}zd(){this.Xa()}Xa(){const d=window.Dg;d&&(d.parentElement.removeChild(d),
window.Dg=null)}async tf(){const d=await Q(this.gb);return{outputPort:d,transferables:[d]}}jf(){if(this.ra)throw Error("not available in worker mode");return this.Ka}lc(d,h,l,n,q){this.pa.postMessage({type:"event",component:d,handler:h,dispatchOpts:n||null,data:l,responseId:null},q)}od(d,h,l,n,q){const u=F++,r=new Promise((z,T)=>{E.set(u,{resolve:z,reject:T})});this.pa.postMessage({type:"event",component:d,handler:h,dispatchOpts:n||null,data:l,responseId:u},q);return r}["_OnMessageFromRuntime"](d){const h=
d.type;if("event"===h)return this.yf(d);if("result"===h)this.Lf(d);else if("runtime-ready"===h)this.Mf();else if("alert-error"===h)this.Xa(),alert(d.message);else if("creating-runtime"===h)this.zd();else throw Error(`unknown message '${h}'`);}yf(d){const h=d.component,l=d.handler,n=d.data,q=d.responseId;if(d=y.get(h))if(d=d.get(l)){var u=null;try{u=d(n)}catch(r){console.error(`Exception in '${h}' handler '${l}':`,r);null!==q&&this.Fb(q,!1,""+r);return}if(null===q)return u;u&&u.then?u.then(r=>this.Fb(q,
!0,r)).catch(r=>{console.error(`Rejection from '${h}' handler '${l}':`,r);this.Fb(q,!1,""+r)}):this.Fb(q,!0,u)}else console.warn(`[DOM] No handler '${l}' for component '${h}'`);else console.warn(`[DOM] No event handlers for component '${h}'`)}Fb(d,h,l){let n;l&&l.transferables&&(n=l.transferables);this.pa.postMessage({type:"result",responseId:d,isOk:h,result:l},n)}Lf(d){const h=d.responseId,l=d.isOk;d=d.result;const n=E.get(h);l?n.resolve(d):n.reject(d);E.delete(h)}C(d,h,l){let n=y.get(d);n||(n=new Map,
y.set(d,n));if(n.has(h))throw Error(`[DOM] Component '${d}' already has handler '${h}'`);n.set(h,l)}static Ca(d){if(C.includes(d))throw Error("DOM handler already added");C.push(d)}vd(){for(const d of this.Nb)if("runtime"===d.Za){this.Pa=d;return}throw Error("cannot find runtime DOM handler");}Ef(d){this.lc("debugger","message",d)}Mf(){for(const d of this.Nb)d.dd()}static jc(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Te(d){this.Na.push(d);
this.Jc()}Xf(d){d=this.Na.indexOf(d);if(-1===d)throw Error("invalid callback");this.Na.splice(d,1);this.Na.length||this.sc()}Jc(){-1===this.Oa&&this.Na.length&&(this.Oa=requestAnimationFrame(this.Bg))}sc(){-1!==this.Oa&&(cancelAnimationFrame(this.Oa),this.Oa=-1)}If(){this.Oa=-1;for(const d of this.Na)d();this.Jc()}va(d){this.Pa.va(d)}Fa(d){this.Pa.Fa(d)}Ic(){this.Pa.Ic()}Ab(d){this.Pa.Ab(d)}Fe(){return!!v["audio/webm; codecs=opus"]}async ug(d){d=await this.od("runtime","opus-decode",{arrayBuffer:d},
null,[d]);return new Float32Array(d)}Ee(d){return/^(?:[a-z\-]+:)?\/\//.test(d)||"data:"===d.substr(0,5)||"blob:"===d.substr(0,5)}md(d){return!this.Ee(d)}async zc(d,h){return"cordova"===this.B&&"module"===h&&(d.startsWith("file:")||"file:"===location.protocol&&this.md(d))?(d.startsWith(this.F)&&(d=d.substr(this.F.length)),d=await this.ub(d),URL.createObjectURL(new Blob([d],{type:"application/javascript"}))):d}async sf(d){const h=d.filename;switch(d.as){case "text":return await this.we(h);case "buffer":return await this.ub(h);
default:throw Error("unsupported type");}}gd(d){const h=window.cordova.file.applicationDirectory+"www/"+d.toLowerCase();return new Promise((l,n)=>{window.resolveLocalFileSystemURL(h,q=>{q.file(l,n)},n)})}async we(d){d=await this.gd(d);return await A(d)}tc(){if(w.length&&!(8<=x)){x++;var d=w.shift();this.$e(d.filename,d.Kg,d.Fg)}}ub(d){return new Promise((h,l)=>{w.push({filename:d,Kg:n=>{x--;this.tc();h(n)},Fg:n=>{x--;this.tc();l(n)}});this.tc()})}async $e(d,h,l){try{const n=await this.gd(d),q=await B(n);
h(q)}catch(n){l(n)}}async Ze(){const d=[];for(const [h,l]of Object.entries(this.ia))d.push(this.Ye(h,l));await Promise.all(d)}async Ye(d,h){if("object"===typeof h)this.ia[d]=new Blob([h.str],{type:h.type}),this.Sb[d]=h.str;else{let l=await this.gf(h);l||(l=this.bf(h));this.ia[d]=l}}async gf(d){try{return await (await fetch(d)).blob()}catch(h){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
h),null}}bf(d){d=this.Rf(d);return this.We(d.data,d.Hg)}Rf(d){var h=d.indexOf(",");if(0>h)throw new URIError("expected comma in data: uri");var l=d.substring(h+1);h=d.substring(5,h).split(";");d=h[0]||"";const n=h[2];l="base64"===h[1]||"base64"===n?atob(l):decodeURIComponent(l);return{Hg:d,data:l}}We(d,h){var l=d.length;let n=l>>2,q=new Uint8Array(l),u=new Uint32Array(q.buffer,0,n),r,z;for(z=r=0;r<n;++r)u[r]=d.charCodeAt(z++)|d.charCodeAt(z++)<<8|d.charCodeAt(z++)<<16|d.charCodeAt(z++)<<24;for(l&=
3;l--;)q[z]=d.charCodeAt(z),++z;return new Blob([q],{type:h})}}}"use strict";
{const f=self.ua;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),c={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(e){return new Promise((k,d)=>{const h=document.createElement("link");h.onload=()=>k(h);h.onerror=l=>d(l);h.rel=
"stylesheet";h.href=e;document.head.appendChild(h)})}function v(e){return new Promise((k,d)=>{const h=new Image;h.onload=()=>k(h);h.onerror=l=>d(l);h.src=e})}async function A(e){e=URL.createObjectURL(e);try{return await v(e)}finally{URL.revokeObjectURL(e)}}function B(e){return new Promise((k,d)=>{let h=new FileReader;h.onload=l=>k(l.target.result);h.onerror=l=>d(l);h.readAsText(e)})}async function w(e,k,d){if(!/firefox/i.test(navigator.userAgent))return await A(e);var h=await B(e);h=(new DOMParser).parseFromString(h,
"image/svg+xml");const l=h.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),q=l.getAttribute("height");if(!n.includes("%")&&!q.includes("%"))return await A(e)}l.setAttribute("width",k+"px");l.setAttribute("height",d+"px");h=(new XMLSerializer).serializeToString(h);e=new Blob([h],{type:"image/svg+xml"});return await A(e)}function x(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["canvas",
"body","html"]);function y(e){C.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function E(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await A(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const k=e.getBoundingClientRect();document.body.removeChild(e);return[k.width,k.height]}};self.C3_RasterSvgImageBlob=async function(e,
k,d,h,l){e=await w(e,k,d);const n=document.createElement("canvas");n.width=h;n.height=l;n.getContext("2d").drawImage(e,0,0,k,d);return n};let F=!1;document.addEventListener("pause",()=>F=!0);document.addEventListener("resume",()=>F=!1);function J(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}f.Ca(class extends self.Da{constructor(e){super(e,"runtime");this.Qd=!0;this.Qa=-1;this.$c="any";this.Hd=this.Id=!1;this.Uc=this.ob=this.za=null;e.C("canvas","update-size",h=>
this.Pf(h));e.C("runtime","invoke-download",h=>this.Cf(h));e.C("runtime","raster-svg-image",h=>this.Jf(h));e.C("runtime","get-svg-image-size",h=>this.Af(h));e.C("runtime","set-target-orientation",h=>this.Nf(h));e.C("runtime","register-sw",()=>this.Kf());e.C("runtime","post-to-debugger",h=>this.Bd(h));e.C("runtime","go-to-script",h=>this.Bd(h));e.C("runtime","before-start-ticking",()=>this.rf());e.C("runtime","debug-highlight",h=>this.uf(h));e.C("runtime","enable-device-orientation",()=>this.Ve());
e.C("runtime","enable-device-motion",()=>this.Ue());e.C("runtime","add-stylesheet",h=>this.qf(h));e.C("runtime","alert",h=>this.Ac(h));e.C("runtime","hide-cordova-splash",()=>this.Bf());const k=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",h=>{const l=h.target;k.has(l.tagName.toLowerCase())||x(l)||h.preventDefault()});const d=e.K;window.addEventListener("selectstart",y);window.addEventListener("gesturehold",y);d.addEventListener("selectstart",y);d.addEventListener("gesturehold",
y);window.addEventListener("touchstart",y,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",y,{passive:!1}),d.addEventListener("pointerdown",y)):d.addEventListener("touchstart",y);this.lb=0;window.addEventListener("mousedown",h=>{1===h.button&&h.preventDefault()});window.addEventListener("mousewheel",E,{passive:!1});window.addEventListener("wheel",E,{passive:!1});window.addEventListener("resize",()=>this.Qf());window.addEventListener("fullscreenchange",()=>this.Cc());
window.addEventListener("webkitfullscreenchange",()=>this.Cc());window.addEventListener("mozfullscreenchange",()=>this.Cc());window.addEventListener("fullscreenerror",h=>this.Dc(h));window.addEventListener("webkitfullscreenerror",h=>this.Dc(h));window.addEventListener("mozfullscreenerror",h=>this.Dc(h));e.kc()&&window.addEventListener("focusout",()=>{{const n=document.activeElement;if(n){var h=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));h="textarea"===
h?!0:"input"===h?l.has(n.type.toLowerCase()||"text"):x(n)}else h=!1}h||(document.scrollingElement.scrollTop=0)});this.La=new Set;this.Tb=new WeakSet;this.oa=!1}rf(){"cordova"===this.v.B?(document.addEventListener("pause",()=>this.Hc(!0)),document.addEventListener("resume",()=>this.Hc(!1))):document.addEventListener("visibilitychange",()=>this.Hc(document.hidden));return{isSuspended:!(!document.hidden&&!F)}}dd(){window.addEventListener("focus",()=>this.Gb("window-focus"));window.addEventListener("blur",
()=>{this.Gb("window-blur",{parentHasFocus:J()});this.lb=0});window.addEventListener("keydown",k=>this.Ad("keydown",k));window.addEventListener("keyup",k=>this.Ad("keyup",k));window.addEventListener("dblclick",k=>this.Ec("dblclick",k,c));window.addEventListener("wheel",k=>this.Gf(k));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",k=>{this.wc(k);this.Wa("pointerdown",k)}),this.v.ra&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.ob=new self.Ke(()=>this.ef(),
5),this.ob.Ld=!0,window.addEventListener("pointerrawupdate",k=>this.Hf(k))):window.addEventListener("pointermove",k=>this.Wa("pointermove",k)),window.addEventListener("pointerup",k=>this.Wa("pointerup",k)),window.addEventListener("pointercancel",k=>this.Wa("pointercancel",k))):(window.addEventListener("mousedown",k=>{this.wc(k);this.Fc("pointerdown",k)}),window.addEventListener("mousemove",k=>this.Fc("pointermove",k)),window.addEventListener("mouseup",k=>this.Fc("pointerup",k)),window.addEventListener("touchstart",
k=>{this.wc(k);this.Eb("pointerdown",k)}),window.addEventListener("touchmove",k=>this.Eb("pointermove",k)),window.addEventListener("touchend",k=>this.Eb("pointerup",k)),window.addEventListener("touchcancel",k=>this.Eb("pointercancel",k)));const e=()=>this.Ic();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}Gb(e,k){t(this,e,k||null,m)}xa(){return this.v.xa()}wa(){return this.v.wa()}Qf(){const e=
this.xa(),k=this.wa();this.Gb("window-resize",{innerWidth:e,innerHeight:k,devicePixelRatio:window.devicePixelRatio});this.v.kc()&&(-1!==this.Qa&&clearTimeout(this.Qa),this.Cd(e,k,0))}Yf(e,k,d){-1!==this.Qa&&clearTimeout(this.Qa);this.Qa=setTimeout(()=>this.Cd(e,k,d),48)}Cd(e,k,d){const h=this.xa(),l=this.wa();this.Qa=-1;h!=e||l!=k?this.Gb("window-resize",{innerWidth:h,innerHeight:l,devicePixelRatio:window.devicePixelRatio}):10>d&&this.Yf(h,l,d+1)}Nf(e){this.$c=e.targetOrientation}qg(){const e=this.$c;
if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(k=>console.warn("[Construct 3] Failed to lock orientation: ",k));else try{let k=!1;screen.lockOrientation?k=screen.lockOrientation(e):screen.webkitLockOrientation?k=screen.webkitLockOrientation(e):screen.mozLockOrientation?k=screen.mozLockOrientation(e):screen.msLockOrientation&&(k=screen.msLockOrientation(e));k||console.warn("[Construct 3] Failed to lock orientation")}catch(k){console.warn("[Construct 3] Failed to lock orientation: ",
k)}}Cc(){const e=f.jc();e&&"any"!==this.$c&&this.qg();t(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.xa(),innerHeight:this.wa()})}Dc(e){console.warn("[Construct 3] Fullscreen request failed: ",e);t(this,"fullscreenerror",{isFullscreen:f.jc(),innerWidth:this.xa(),innerHeight:this.wa()})}Hc(e){e?this.v.sc():this.v.Jc();t(this,"visibilitychange",{hidden:e})}Ad(e,k){"Backspace"===k.key&&y(k);const d=b.get(k.code)||k.code;D(this,e,{code:d,key:k.key,which:k.which,repeat:k.repeat,altKey:k.altKey,
ctrlKey:k.ctrlKey,metaKey:k.metaKey,shiftKey:k.shiftKey,timeStamp:k.timeStamp},c)}Gf(e){t(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,timeStamp:e.timeStamp},c)}Ec(e,k,d){a(k)||D(this,e,{button:k.button,buttons:k.buttons,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,timeStamp:k.timeStamp},d)}Fc(e,k){if(!a(k)){var d=this.lb;"pointerdown"===e&&0!==d?e="pointermove":"pointerup"===
e&&0!==k.buttons&&(e="pointermove");D(this,e,{pointerId:1,pointerType:"mouse",button:k.button,buttons:k.buttons,lastButtons:d,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:k.timeStamp},c);this.lb=k.buttons;this.Ec(k.type,k,g)}}Wa(e,k){if(this.ob&&"pointermove"!==e){var d=this.ob;d.eb||(K(d),d.Qb=Date.now())}d=0;"mouse"===k.pointerType&&(d=this.lb);D(this,e,{pointerId:k.pointerId,pointerType:k.pointerType,
button:k.button,buttons:k.buttons,lastButtons:d,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:k.width||0,height:k.height||0,pressure:k.pressure||0,tangentialPressure:k.tangentialPressure||0,tiltX:k.tiltX||0,tiltY:k.tiltY||0,twist:k.twist||0,timeStamp:k.timeStamp},c);"mouse"===k.pointerType&&(d="mousemove","pointerdown"===e?d="mousedown":"pointerup"===e&&(d="mouseup"),this.Ec(d,k,g),this.lb=k.buttons)}Hf(e){this.Uc=e;e=this.ob;if(-1===e.Ra){var k=Date.now(),d=k-e.Qb,h=e.wg;
d>=h&&e.Ld?(e.Qb=k,e.eb=!0,e.Lc(),e.eb=!1):e.Ra=self.setTimeout(e.ce,Math.max(h-d,4))}}ef(){this.Wa("pointermove",this.Uc);this.Uc=null}Eb(e,k){for(let d=0,h=k.changedTouches.length;d<h;++d){const l=k.changedTouches[d];D(this,e,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:k.timeStamp},c)}}wc(e){window!==window.top&&window.focus();this.yd(e.target)&&document.activeElement&&!this.yd(document.activeElement)&&document.activeElement.blur()}yd(e){return!e||e===document||e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}Ve(){this.Id||(this.Id=!0,window.addEventListener("deviceorientation",e=>this.wf(e)),window.addEventListener("deviceorientationabsolute",e=>this.xf(e)))}Ue(){this.Hd||(this.Hd=!0,window.addEventListener("devicemotion",
e=>this.vf(e)))}wf(e){t(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},c)}xf(e){t(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},c)}vf(e){let k=null;var d=e.acceleration;d&&(k={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var h=e.accelerationIncludingGravity;h&&(d={x:h.x||
0,y:h.y||0,z:h.z||0});h=null;const l=e.rotationRate;l&&(h={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});t(this,"devicemotion",{acceleration:k,accelerationIncludingGravity:d,rotationRate:h,interval:e.interval,timeStamp:e.timeStamp},c)}Pf(e){const k=this.v.K;k.style.width=e.styleWidth+"px";k.style.height=e.styleHeight+"px";k.style.marginLeft=e.marginLeft+"px";k.style.marginTop=e.marginTop+"px";this.Qd&&(k.style.display="",this.Qd=!1)}Cf(e){const k=e.url;e=e.filename;const d=document.createElement("a"),
h=document.body;d.textContent=e;d.href=k;d.download=e;h.appendChild(d);d.click();h.removeChild(d)}async Jf(e){var k=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);k=k?await createImageBitmap(e,k):await createImageBitmap(e);return{imageBitmap:k,transferables:[k]}}async Af(e){return await self.C3_GetSvgImageSize(e.blob)}async qf(e){await p(e.url)}Ic(){var e=[...this.La];this.La.clear();if(!this.oa)for(const k of e)(e=k.play())&&
e.catch(()=>{this.Tb.has(k)||this.La.add(k)})}va(e){if("function"!==typeof e.play)throw Error("missing play function");this.Tb.delete(e);let k;try{k=e.play()}catch(d){this.La.add(e);return}k&&k.catch(()=>{this.Tb.has(e)||this.La.add(e)})}Fa(e){this.La.delete(e);this.Tb.add(e)}Ab(e){this.oa=!!e}Bf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}uf(e){if(e.show){this.za||(this.za=document.createElement("div"),this.za.id="inspectOutline",document.body.appendChild(this.za));
var k=this.za;k.style.display="";k.style.left=e.left-1+"px";k.style.top=e.top-1+"px";k.style.width=e.width+2+"px";k.style.height=e.height+2+"px";k.textContent=e.name}else this.za&&(this.za.style.display="none")}Kf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Bd(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}nf(e,k){return this.v.od(this.Za,"js-invoke-function",{name:e,params:k},void 0,void 0)}Ac(e){alert(e.message)}})}"use strict";
async function O(f){if(f.vg)throw Error("already initialised");f.vg=!0;var a=f.Xb.vc("dispatchworker.js");f.Nc=await f.Xb.cc(a,f.F,{name:"DispatchWorker"});a=new MessageChannel;f.Rc=a.port1;f.Nc.postMessage({type:"_init","in-port":a.port2},[a.port2]);f.Yc=await Q(f)}function P(f){return[f.Rc,f.Yc]}
async function Q(f){const a=f.Rd.length;var b=f.Xb.vc("jobworker.js");b=await f.Xb.cc(b,f.F,{name:"JobWorker"+a});const c=new MessageChannel,g=new MessageChannel;f.Nc.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":g.port2},[c.port2,g.port2]);f.Rd.push(b);return g.port1}
self.Ge=class{constructor(f){this.Xb=f;this.F=f.F;this.F="preview"===f.B?this.F+"c3/workers/":this.F+f.Yb;this.yg=Math.min(navigator.hardwareConcurrency||2,16);this.Nc=null;this.Rd=[];this.Yc=this.Rc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ua({Lg:!1,Mg:"workermain.js",Sa:["scripts/c3runtime.js"],tb:[],ee:"",fe:"module",Ig:"scripts/",cd:[],de:"html5"}));"use strict";
async function R(f,a){a=a.type;let b=!0;0===a?b=await S():1===a&&(b=await U());t(f,"permission-result",{type:a,result:b})}async function S(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request orientation permission: ",f),!1}}
async function U(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request motion permission: ",f),!1}}self.ua.Ca(class extends self.Da{constructor(f){super(f,"touch");G(this,"request-permission",a=>R(this,a))}});"use strict";
{function f(a){a.stopPropagation()}self.ua.Ca(class extends self.xe{constructor(a){super(a,"sliderbar")}hd(a,b){const c=document.createElement("input");c.type="range";c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("touchstart",f);c.addEventListener("touchmove",f);c.addEventListener("touchend",f);c.addEventListener("mousedown",f);c.addEventListener("mouseup",f);c.addEventListener("keydown",f);c.addEventListener("keyup",f);c.addEventListener("click",
()=>{var g;g||(g={});g.elementId=a;D(this,"click",g)});c.addEventListener("change",()=>M(this,"change",a,{value:parseFloat(c.value)}));c.addEventListener("input",()=>M(this,"input",a,{value:parseFloat(c.value)}));b.id&&(c.id=b.id);this.rc(c,b);return c}rc(a,b){a.max=b.max;a.min=b.min;a.step=b.step;a.value=b.value;a.disabled=!b.isEnabled;a.title=b.title}})}"use strict";
{const f=180/Math.PI;self.ea=class extends self.Da{constructor(a){super(a,"audio");this.Mb=this.f=null;this.Ob=this.Qc=!1;this.qa=()=>this.rg();this.ba=[];this.D=[];this.ha=null;this.Sd="";this.Td=-1;this.nb=new Map;this.Vc=1;this.oa=!1;this.ad=0;this.$b=1;this.Oc=0;this.Vd="HRTF";this.Md="inverse";this.Wd=600;this.Ud=1E4;this.Yd=1;this.Od=this.Zc=!1;this.ae=this.v.Fe();this.ca=new Map;this.Ia=new Set;this.Sc=!1;this.Wc="";this.Aa=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.Ff(b,c);this.Lb=null;
self.C3Audio_GetOutputStream=()=>this.zf();self.C3Audio_DOMInterface=this;H(this,[["create-audio-context",b=>this.af(b)],["play",b=>this.Sf(b)],["stop",b=>this.og(b)],["stop-all",()=>this.pg()],["set-paused",b=>this.hg(b)],["set-volume",b=>this.mg(b)],["fade-volume",b=>this.ff(b)],["set-master-volume",b=>this.fg(b)],["set-muted",b=>this.gg(b)],["set-silent",b=>this.jg(b)],["set-looping",b=>this.eg(b)],["set-playback-rate",b=>this.ig(b)],["seek",b=>this.Zf(b)],["preload",b=>this.Tf(b)],["unload",b=>
this.sg(b)],["unload-all",()=>this.tg()],["set-suspended",b=>this.kg(b)],["add-effect",b=>this.td(b)],["set-effect-param",b=>this.bg(b)],["remove-effects",b=>this.Vf(b)],["tick",b=>this.Of(b)],["load-state",b=>this.Df(b)]])}async af(a){a.isiOSCordova&&(this.Zc=!0);this.ad=a.timeScaleMode;this.Vd=["equalpower","HRTF","soundfield"][a.panningModel];this.Md=["linear","inverse","exponential"][a.distanceModel];this.Wd=a.refDistance;this.Ud=a.maxDistance;this.Yd=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.ae||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.ud();this.f.onstatechange=()=>{"running"!==this.f.state&&this.ud()};this.Mb=this.f.createGain();this.Mb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.dc();try{await Promise.all(a.preloadList.map(c=>this.Cb(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.f.sampleRate}}ud(){this.Ob||(this.Qc=!1,window.addEventListener("pointerup",this.qa,!0),window.addEventListener("touchend",this.qa,!0),window.addEventListener("click",this.qa,!0),window.addEventListener("keydown",this.qa,!0),this.Ob=!0)}cf(){this.Ob&&(this.Qc=!0,window.removeEventListener("pointerup",this.qa,!0),window.removeEventListener("touchend",
this.qa,!0),window.removeEventListener("click",this.qa,!0),window.removeEventListener("keydown",this.qa,!0),this.Ob=!1)}rg(){if(!this.Qc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.cf()}}W(){return this.f}dc(){return this.f.currentTime}sa(){return this.Mb}kd(a){return(a=this.ca.get(a.toLowerCase()))?a[0].P():this.sa()}ge(a,b){a=a.toLowerCase();let c=this.ca.get(a);
c||(c=[],this.ca.set(a,c));b.dg(c.length);b.lg(a);c.push(b);this.Ed(a)}Ed(a){let b=this.sa();const c=this.ca.get(a);if(c&&c.length){b=c[0].P();for(let g=0,m=c.length;g<m;++g){const p=c[g];g+1===m?p.S(this.sa()):p.S(c[g+1].P())}}for(const g of this.ma(a))g.Le(b);this.Aa&&this.Wc===a&&(this.Aa.disconnect(),this.Aa.connect(b))}wb(){return this.Vc}xb(){return this.oa}cg(){this.Od=!0}ze(a,b){return b?this.v.ug(a).then(c=>{const g=this.f.createBuffer(1,c.length,48E3);g.getChannelData(0).set(c);return g}):
new Promise((c,g)=>{this.f.decodeAudioData(a,c,g)})}va(a){this.v.va(a)}Fa(a){this.v.Fa(a)}pd(a){let b=0;for(let c=0,g=this.D.length;c<g;++c){const m=this.D[c];this.D[b]=m;m.L===a?m.c():++b}this.D.length=b}Me(){let a=0;for(let b=0,c=this.ba.length;b<c;++b){const g=this.ba[b];this.ba[a]=g;g.ta()?g.c():++a}this.ba.length=a}*ma(a){if(a)for(const b of this.D)self.ea.Ae(b.$,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Cb(a,b,c,g,m){for(const p of this.ba)if(p.Ua()===b)return await V(p),
p;if(m)return null;g&&(this.Zc||this.Od)&&this.Me();m="audio/webm; codecs=opus"===c&&!this.ae;g&&m&&this.cg();a=!g||this.Zc||m?new self.ue(this,a,b,c,g,m):new self.se(this,a,b,c,g);this.ba.push(a);await V(a);return a}async uc(a,b,c,g,m){for(const p of this.D)if(p.Ua()===b&&(p.bc()||m))return p.Oe(g),p;a=await this.Cb(a,b,c,m);g="html5"===a.Kc?new self.te(a.i,a,g):new self.ve(a.i,a,g);this.D.push(g);return g}Se(a){let b=this.nb.get(a);if(!b){let c=null;b={bd:0,promise:new Promise(g=>c=g),resolve:c};
this.nb.set(a,b)}b.bd++}Wf(a){const b=this.nb.get(a);if(!b)throw Error("expected pending tag");b.bd--;0===b.bd&&(b.resolve(),this.nb.delete(a))}qc(a){a||(a=this.Sd);return(a=this.nb.get(a))?a.promise:Promise.resolve()}Db(){if(0<this.Ia.size)I(this);else for(const a of this.D)if(a.ld()){I(this);break}}Ga(){for(var a of this.Ia)a.Ga();a=this.dc();for(var b of this.D)b.Ga(a);b=this.D.filter(c=>c.ld()).map(c=>c.Ta());t(this,"state",{tickCount:this.Td,audioInstances:b,analysers:[...this.Ia].map(c=>c.Ce())});
0===b.length&&0===this.Ia.size&&this.Pb&&(this.v.Xf(this.be),this.Pb=!1)}mc(a,b,c){t(this,"trigger",{type:a,tag:b,aiid:c})}async Sf(a){const b=a.originalUrl,c=a.url,g=a.type,m=a.isMusic,p=a.tag,v=a.isLooping,A=a.vol,B=a.pos,w=a.panning;let x=a.off;0<x&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+this.f.currentTime);this.Sd=p;this.Se(p);try{this.ha=await this.uc(b,c,g,p,m),w?(this.ha.zb(!0),this.ha.Ne(w.x,
w.y,w.angle,w.innerAngle,w.outerAngle,w.outerGain),w.hasOwnProperty("uid")&&this.ha.Pe(w.uid)):this.ha.zb(!1),this.ha.Play(v,A,B,x)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.Wf(p)}I(this)}og(a){a=a.tag;for(const b of this.ma(a))b.na()}pg(){for(const a of this.D)a.na()}hg(a){const b=a.tag;a=a.paused;for(const c of this.ma(b))a?c.Va():c.yb();this.Db()}mg(a){const b=a.tag;a=a.vol;for(const c of this.ma(b))c.Bb(a)}async ff(a){const b=a.tag,c=a.vol,
g=a.duration;a=a.stopOnEnd;await this.qc(b);for(const m of this.ma(b))m.Be(c,g,a);this.Db()}fg(a){this.Vc=a.vol;for(const b of this.D)b.Ib()}gg(a){const b=a.tag;a=a.isMuted;for(const c of this.ma(b))c.qd(a)}jg(a){this.oa=a.isSilent;this.v.Ab(this.oa);for(const b of this.D)b.Hb()}eg(a){const b=a.tag;a=a.isLooping;for(const c of this.ma(b))c.oc(a)}async ig(a){const b=a.tag;a=a.rate;await this.qc(b);for(const c of this.ma(b))c.sd(a)}async Zf(a){const b=a.tag;a=a.pos;await this.qc(b);for(const c of this.ma(b))c.nc(a)}async Tf(a){const b=
a.originalUrl,c=a.url,g=a.type;a=a.isMusic;try{await this.uc(b,c,g,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async sg(a){if(a=await this.Cb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.ba.indexOf(a),-1!==a&&this.ba.splice(a,1)}tg(){for(const a of this.ba)a.c();this.ba.length=0}kg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.pc(a);a&&this.f.suspend&&this.f.suspend()}Of(a){this.$b=a.timeScale;this.Oc=a.gameTime;this.Td=a.tickCount;if(0!==
this.ad)for(var b of this.D)b.Ha();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const g of this.D)g.ga===a&&g.rd(c.x,c.y,c.angle)}}async td(a){var b=a.type;const c=a.tag;var g=a.params;if("filter"===b)g=new self.me(this,...g);else if("delay"===b)g=new self.ke(this,...g);else if("convolution"===b){b=null;try{b=await this.Cb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",
m);return}g=new self.je(this,b.aa,...g);g.$f(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.ne(this,...g);else if("phaser"===b)g=new self.pe(this,...g);else if("gain"===b)g=new self.oe(this,...g);else if("tremolo"===b)g=new self.re(this,...g);else if("ringmod"===b)g=new self.qe(this,...g);else if("distortion"===b)g=new self.le(this,...g);else if("compressor"===b)g=new self.ie(this,...g);else if("analyser"===b)g=new self.he(this,...g);else throw Error("invalid effect type");this.ge(c,
g);this.Dd()}bg(a){const b=a.index,c=a.param,g=a.value,m=a.ramp,p=a.time;a=this.ca.get(a.tag);!a||0>b||b>=a.length||(a[b].X(c,g,m,p),this.Dd())}Vf(a){a=a.tag.toLowerCase();const b=this.ca.get(a);if(b&&b.length){for(const c of b)c.c();this.ca.delete(a);this.Ed(a)}}Re(a){this.Ia.add(a);this.Db()}Uf(a){this.Ia.delete(a)}Dd(){this.Sc||(this.Sc=!0,Promise.resolve().then(()=>this.df()))}df(){const a={};for(const [b,c]of this.ca)a[b]=c.map(g=>g.Ta());t(this,"fxstate",{fxstate:a});this.Sc=!1}async Df(a){const b=
a.saveLoadMode;if(3!==b)for(var c of this.D)c.ta()&&1===b||(c.ta()||2!==b)&&c.na();for(const g of this.ca.values())for(const m of g)m.c();this.ca.clear();this.$b=a.timeScale;this.Oc=a.gameTime;c=a.listenerPos;this.f.listener.setPosition(c[0],c[1],c[2]);this.oa=a.isSilent;this.v.Ab(this.oa);this.Vc=a.masterVolume;c=[];for(const g of Object.values(a.effects))c.push(Promise.all(g.map(m=>this.td(m))));await Promise.all(c);await Promise.all(a.playing.map(g=>this.pf(g,b)));this.Db()}async pf(a,b){if(3!==
b){var c=a.bufferOriginalUrl,g=a.bufferUrl,m=a.bufferType,p=a.isMusic,v=a.tag,A=a.isLooping,B=a.volume,w=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.uc(c,g,m,v,p)}catch(x){console.error("[Construct 3] Audio: error loading audio state: ",x);return}b.Je(a.pan);b.Play(A,B,w,0);a.isPlaying||b.Va();b.yc(a)}}}Ff(a,b){this.Aa&&this.Aa.disconnect();this.Wc=b.toLowerCase();this.Aa=this.f.createMediaStreamSource(a);this.Aa.connect(this.kd(this.Wc))}zf(){this.Lb||(this.Lb=this.f.createMediaStreamDestination(),
this.Mb.connect(this.Lb));return this.Lb.stream}static Ae(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Qe(a){return a*f}static ye(a){return Math.pow(10,a/20)}static jd(a){return Math.max(Math.min(self.ea.ye(a),1),0)}static Ie(a){return Math.log(a)/Math.log(10)*20}static He(a){return self.ea.Ie(Math.max(Math.min(a,1),0))}static Eg(a,b){return 1-Math.exp(-b*a)}};self.ua.Ca(self.ea)}"use strict";function V(f){f.Rb||(f.Rb=f.xc());return f.Rb}
self.ed=class{constructor(f,a,b,c,g){this.i=f;this.Ag=a;this.Ba=b;this.R=c;this.xg=g;this.Kc="";this.Rb=null}c(){this.Rb=this.i=null}xc(){}W(){return this.i.W()}fc(){return this.Ag}Ua(){return this.Ba}ec(){return this.R}ta(){return this.xg}fa(){}};"use strict";
self.se=class extends self.ed{constructor(f,a,b,c,g){super(f,a,b,c,g);this.Kc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.hb=this.ib=null;this.J.addEventListener("canplaythrough",()=>!0);this.mb=this.W().createGain();this.kb=null;this.J.addEventListener("canplay",()=>{this.ib&&(this.ib(),this.hb=this.ib=null);!this.kb&&this.J&&(this.kb=this.W().createMediaElementSource(this.J),this.kb.connect(this.mb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.Ba}' error: `,m);this.hb&&(this.hb(m),this.hb=this.ib=null)})}c(){this.i.pd(this);this.mb.disconnect();this.mb=null;this.kb.disconnect();this.kb=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}xc(){return new Promise((f,a)=>{this.ib=f;this.hb=a;this.J.src=this.Ba})}O(){return this.J}fa(){return this.J.duration}};"use strict";
async function W(f){if(f.ya)return f.ya;var a=f.i.v;if("cordova"===a.B&&a.md(f.Ba)&&"file:"===location.protocol)f.ya=await a.ub(f.Ba);else{a=await fetch(f.Ba);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);f.ya=await a.arrayBuffer()}}async function X(f){if(f.aa)return f.aa;f.aa=await f.i.ze(f.ya,f.zg);f.ya=null}
self.ue=class extends self.ed{constructor(f,a,b,c,g,m){super(f,a,b,c,g);this.Kc="webaudio";this.aa=this.ya=null;this.zg=!!m}c(){this.i.pd(this);this.aa=this.ya=null;super.c()}async xc(){try{await W(this),await X(this)}catch(f){console.error(`[Construct 3] Failed to load audio '${this.Ba}': `,f)}}fa(){return this.aa?this.aa.duration:0}};"use strict";
{let f=0;self.fd=class{constructor(a,b,c){this.i=a;this.L=b;this.$=c;this.Jb=f++;this.M=this.W().createGain();this.M.connect(this.sa());this.A=null;this.fb=!1;this.ka=[0,0,0];this.ja=[0,0,0];this.H=!0;this.V=this.la=this.G=!1;this.qb=1;this.Ja=!1;this.Z=1;a=this.i.ad;this.Tc=1===a&&!this.ta()||2===a;this.bb=this.ga=-1;this.$d=!1}c(){this.L=this.i=null;this.A&&(this.A.disconnect(),this.A=null);this.M.disconnect();this.M=null}W(){return this.i.W()}sa(){return this.i.kd(this.$)}wb(){return this.i.wb()}vb(){return this.Tc?
this.i.Oc:performance.now()/1E3}fc(){return this.L.fc()}Ua(){return this.L.Ua()}ec(){return this.L.ec()}ta(){return this.L.ta()}Oe(a){this.$=a}T(){}bc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}ld(){return!this.H&&!this.T()}Ea(){}fa(){return this.L.fa()}Play(){}na(){}Va(){}yb(){}Bb(a){this.qb=a;this.M.gain.cancelScheduledValues(0);this.bb=-1;this.M.gain.value=this.hc()}Be(a,b,c){if(!this.Ja){a*=this.wb();var g=this.M.gain;g.cancelScheduledValues(0);var m=this.i.dc();b=m+b;g.setValueAtTime(g.value,
m);g.linearRampToValueAtTime(a,b);this.qb=a;this.bb=b;this.$d=c}}Ib(){this.Bb(this.qb)}Ga(a){-1!==this.bb&&a>=this.bb&&(this.bb=-1,this.$d&&this.na(),this.i.mc("fade-ended",this.$,this.Jb))}hc(){const a=this.qb*this.wb();return isFinite(a)?a:0}qd(a){a=!!a;this.Ja!==a&&(this.Ja=a,this.Hb())}xb(){return this.i.xb()}Hb(){}oc(){}sd(a){this.Z!==a&&(this.Z=a,this.Ha())}Ha(){}nc(){}pc(){}zb(a){a=!!a;this.fb!==a&&((this.fb=a)?(this.A||(this.A=this.W().createPanner(),this.A.panningModel=this.i.Vd,this.A.distanceModel=
this.i.Md,this.A.refDistance=this.i.Wd,this.A.maxDistance=this.i.Ud,this.A.rolloffFactor=this.i.Yd),this.M.disconnect(),this.M.connect(this.A),this.A.connect(this.sa())):(this.A.disconnect(),this.M.disconnect(),this.M.connect(this.sa())))}Ne(a,b,c,g,m,p){this.fb&&(this.rd(a,b,c),a=self.ea.Qe,this.A.coneInnerAngle=a(g),this.A.coneOuterAngle=a(m),this.A.coneOuterGain=p)}rd(a,b,c){this.fb&&(this.ka[0]=a,this.ka[1]=b,this.ka[2]=0,this.ja[0]=Math.cos(c),this.ja[1]=Math.sin(c),this.ja[2]=0,this.A.setPosition(...this.ka),
this.A.setOrientation(...this.ja))}Pe(a){this.ga=a}ic(){}Le(a){const b=this.A||this.M;b.disconnect();b.connect(a)}Ta(){return{aiid:this.Jb,tag:this.$,duration:this.fa(),volume:this.qb,isPlaying:this.IsPlaying(),playbackTime:this.Ea(),playbackRate:this.Z,uid:this.ga,bufferOriginalUrl:this.fc(),bufferUrl:"",bufferType:this.ec(),isMusic:this.ta(),isLooping:this.V,isMuted:this.Ja,resumePosition:this.ic(),pan:this.De()}}yc(a){this.sd(a.playbackRate);this.qd(a.isMuted)}De(){if(!this.A)return null;const a=
this.A;return{pos:this.ka,orient:this.ja,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}Je(a){if(a){this.zb(!0);a=this.A;var b=a.pos;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];b=a.orient;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];a.setPosition(...this.ka);a.setOrientation(...this.ja);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ga=a.uid}else this.zb(!1)}}}"use strict";
self.te=class extends self.fd{constructor(f,a,b){super(f,a,b);this.L.mb.connect(this.M);this.L.onended=()=>this.Bc()}c(){this.na();this.L.mb.disconnect();super.c()}O(){return this.L.O()}Bc(){this.H=!0;this.ga=-1;this.i.mc("ended",this.$,this.Jb)}T(){return this.O().ended}bc(){return this.H?!0:this.T()}Ea(f){let a=this.O().currentTime;f&&(a*=this.Z);this.V||(a=Math.min(a,this.fa()));return a}Play(f,a,b){const c=this.O();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==f&&(c.loop=f);this.Bb(a);c.muted&&
(c.muted=!1);if(c.currentTime!==b)try{c.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Ua()}' to position '${b}': `,g)}this.i.va(c);this.G=this.H=!1;this.V=f;this.Z=1}na(){const f=this.O();f.paused||f.pause();this.i.Fa(f);this.H=!0;this.G=!1;this.ga=-1}Va(){if(!(this.G||this.H||this.T())){var f=this.O();f.paused||f.pause();this.i.Fa(f);this.G=!0}}yb(){!this.G||this.H||this.T()||(this.i.va(this.O()),this.G=!1)}Hb(){this.O().muted=this.Ja||this.xb()}oc(f){f=!!f;
this.V!==f&&(this.V=f,this.O().loop=f)}Ha(){let f=this.Z;this.Tc&&(f*=this.i.$b);try{this.O().playbackRate=f}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${f}':`,a)}}nc(f){if(!this.H&&!this.T())try{this.O().currentTime=f}catch(a){console.warn(`[Construct 3] Error seeking audio to '${f}': `,a)}}ic(){return this.Ea()}pc(f){f?this.IsPlaying()?(this.O().pause(),this.la=!0):this.la=!1:this.la&&(this.i.va(this.O()),this.la=!1)}};"use strict";
function Y(f){f.j&&f.j.disconnect();f.j=null;f.Ya=null}
self.ve=class extends self.fd{constructor(f,a,b){super(f,a,b);this.j=null;this.Ub=c=>this.Bc(c);this.Pc=!0;this.Ya=null;this.N=this.Zb=0;this.Xc=1}c(){this.na();Y(this);this.Ub=null;super.c()}Bc(f){this.G||this.la||f.target!==this.Ya||(this.H=this.Pc=!0,this.ga=-1,Y(this),this.i.mc("ended",this.$,this.Jb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Pc}bc(){return!this.j||this.H?!0:this.T()}Ea(f){let a;a=this.G?this.N:this.vb()-this.Zb;f&&(a*=this.Z);this.V||(a=Math.min(a,this.fa()));return a}Play(f,
a,b,c){this.Xc=1;this.Bb(a);Y(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.aa;this.j.connect(this.M);this.Ya=this.j;this.j.onended=this.Ub;this.j.loop=f;this.j.start(c,b);this.G=this.H=this.Pc=!1;this.V=f;this.Z=1;this.Zb=this.vb()-b}na(){if(this.j)try{this.j.stop(0)}catch(f){}this.H=!0;this.G=!1;this.ga=-1}Va(){this.G||this.H||this.T()||(this.N=this.Ea(!0),this.V&&(this.N%=this.fa()),this.G=!0,this.j.stop(0))}yb(){!this.G||this.H||this.T()||(Y(this),this.j=this.W().createBufferSource(),
this.j.buffer=this.L.aa,this.j.connect(this.M),this.Ya=this.j,this.j.onended=this.Ub,this.j.loop=this.V,this.Ib(),this.Ha(),this.Zb=this.vb()-this.N/(this.Z||.001),this.j.start(0,this.N),this.G=!1)}hc(){return super.hc()*this.Xc}Hb(){this.Xc=this.Ja||this.xb()?0:1;this.Ib()}oc(f){f=!!f;this.V!==f&&(this.V=f,this.j&&(this.j.loop=f))}Ha(){let f=this.Z;this.Tc&&(f*=this.i.$b);this.j&&(this.j.playbackRate.value=f)}nc(f){this.H||this.T()||(this.G?this.N=f:(this.Va(),this.N=f,this.yb()))}ic(){return this.N}pc(f){f?
this.IsPlaying()?(this.la=!0,this.N=this.Ea(!0),this.V&&(this.N%=this.fa()),this.j.stop(0)):this.la=!1:this.la&&(Y(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.aa,this.j.connect(this.M),this.Ya=this.j,this.j.onended=this.Ub,this.j.loop=this.V,this.Ib(),this.Ha(),this.Zb=this.vb()-this.N/(this.Z||.001),this.j.start(0,this.N),this.la=!1)}yc(f){super.yc(f);this.N=f.resumePosition}};"use strict";
{class f{constructor(a){this.i=a;this.f=a.W();this.Pd=-1;this.R=this.$="";this.g=null}c(){this.f=null}dg(a){this.Pd=a}lg(a){this.$=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,c,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var m=this.f.currentTime;g+=m;switch(c){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,g)}}}Ta(){return{type:this.R,tag:this.$,params:this.g}}}
self.me=class extends f{constructor(a,b,c,g,m,p,v){super(a);this.R="filter";this.g=[b,c,g,m,p,v];this.l=this.o();this.b=this.o();this.b.gain.value=v;this.a=this.o();this.a.gain.value=1-v;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=c;this.u.detune.value=g;this.u.Q.value=m;this.u.gain.vlaue=p;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,c,g);break;case 2:this.g[2]=b;this.m(this.u.detune,b,c,g);break;case 3:this.g[3]=b;this.m(this.u.Q,b,c,g);break;case 4:this.g[4]=b,this.m(this.u.gain,b,c,g)}}};self.ke=class extends f{constructor(a,b,c,g){super(a);this.R="delay";this.g=[b,c,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.jb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.ab=this.o();this.ab.gain.value=c;this.l.connect(this.jb);this.l.connect(this.a);this.jb.connect(this.b);this.jb.connect(this.U);this.U.connect(this.ab);this.ab.connect(this.jb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.jb.disconnect();this.U.disconnect();this.ab.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){const m=self.ea.jd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 4:this.g[1]=m(b);this.m(this.ab.gain,m(b),c,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,c,g)}}};self.je=class extends f{constructor(a,b,c,g){super(a);this.R="convolution";this.g=[c,g];this.Kd=this.Jd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.$a=this.f.createConvolver();this.$a.normalize=c;this.$a.buffer=b;this.l.connect(this.$a);this.l.connect(this.a);this.$a.connect(this.b)}c(){this.l.disconnect();this.$a.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}$f(a,b){this.Jd=a;this.Kd=b}Ta(){const a=
super.Ta();a.bufferOriginalUrl=this.Jd;a.bufferUrl="";a.bufferType=this.Kd;return a}};self.ne=class extends f{constructor(a,b,c,g,m,p){super(a);this.R="flanger";this.g=[b,c,g,m,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.cb=this.o();this.cb.gain.value=m;this.U=this.f.createDelay(b+c);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.I=this.o();this.I.gain.value=c;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.cb);this.cb.connect(this.U);this.s.connect(this.I);this.I.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.cb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,c,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,c,g);break;case 8:this.g[3]=b/100,this.m(this.cb.gain,b/100,c,g)}}};self.pe=class extends f{constructor(a,b,c,g,m,p,v){super(a);this.R="phaser";this.g=[b,c,g,m,p,v];this.l=this.o();this.a=this.o();this.a.gain.value=1-v/2;this.b=this.o();this.b.gain.value=v/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
c;this.u.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=p;this.I=this.o();this.I.gain.value=m;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.I);this.I.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,c,g);break;case 2:this.g[1]=b;this.m(this.u.detune,b,c,g);break;case 3:this.g[2]=b;this.m(this.u.Q,b,c,g);break;case 6:this.g[3]=b;this.m(this.I.gain,b,c,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,c,g)}}};self.oe=class extends f{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,c,g){const m=self.ea.jd;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),c,g)}}};self.re=class extends f{constructor(a,b,c){super(a);this.R="tremolo";this.g=[b,c];this.h=this.o();this.h.gain.value=1-c/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.I=this.o();this.I.gain.value=c/2;this.s.connect(this.I);this.I.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,c,g);this.m(this.I.gain,b/2,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.qe=class extends f{constructor(a,b,c){super(a);this.R="ringmod";this.g=[b,c];this.l=this.o();this.b=this.o();this.b.gain.value=c;this.a=this.o();this.a.gain.value=1-c;this.pb=this.o();this.pb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.pb.gain);this.s.start(0);this.l.connect(this.pb);this.l.connect(this.a);this.pb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.pb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,c,g);
this.m(this.a.gain,1-b,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.le=class extends f{constructor(a,b,c,g,m,p){super(a);this.R="distortion";this.g=[b,c,g,m,p];this.l=this.o();this.Wb=this.o();this.Vb=this.o();this.ag(g,m);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.ac=this.f.createWaveShaper();this.Mc=new Float32Array(65536);this.hf(b,c);this.ac.curve=this.Mc;this.l.connect(this.Wb);this.l.connect(this.a);this.Wb.connect(this.ac);this.ac.connect(this.Vb);
this.Vb.connect(this.b)}c(){this.l.disconnect();this.Wb.disconnect();this.ac.disconnect();this.Vb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}ag(a,b){.01>a&&(a=.01);this.Wb.gain.value=a;this.Vb.gain.value=Math.pow(1/a,.6)*b}hf(a,b){for(let c=0;32768>c;++c){let g=c/32768;g=this.ng(g,a,b);this.Mc[32768+c]=g;this.Mc[32768-c-1]=-g}}ng(a,b,c){c=1.05*c*b-b;const g=0>a?-a:a;return(g<b?g:b+c*self.ea.Eg(g-b,1/c))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}};self.ie=class extends f{constructor(a,b,c,g,m,p){super(a);this.R="compressor";this.g=[b,c,g,m,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=c;this.h.ratio.value=g;this.h.attack.value=m;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.he=class extends f{constructor(a,b,c){super(a);this.R="analyser";this.g=[b,c];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=c;this.Nd=new Float32Array(this.h.frequencyBinCount);this.Zd=new Uint8Array(b);this.Xd=this.Ma=0;this.i.Re(this)}c(){this.i.Uf(this);this.h.disconnect();super.c()}Ga(){this.h.getFloatFrequencyData(this.Nd);this.h.getByteTimeDomainData(this.Zd);const a=this.h.fftSize;let b=this.Ma=0;for(var c=0;c<a;++c){let g=(this.Zd[c]-128)/128;0>g&&(g=-g);
this.Ma<g&&(this.Ma=g);b+=g*g}c=self.ea.He;this.Ma=c(this.Ma);this.Xd=c(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Ce(){return{tag:this.$,index:this.Pd,peak:this.Ma,rms:this.Xd,binCount:this.h.frequencyBinCount,freqBins:this.Nd}}}}"use strict";function Z(f){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>t(f,"sw-message",a.data))}
function aa(f){f=f.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(f):screen.webkitLockOrientation?a=screen.webkitLockOrientation(f):screen.mozLockOrientation?a=screen.mozLockOrientation(f):screen.msLockOrientation&&(a=screen.msLockOrientation(f));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.ua.Ca(class extends self.Da{constructor(f){super(f,"browser");this.B="";H(this,[["get-initial-state",a=>{this.B=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>Z(this)],
["alert",a=>this.Ac(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Gc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>aa(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===b)window.forward();else if("home"===b)window.home();else if("reload"===b)location.reload();else if("url"===b){b=a.url;var c=a.target;a=a.exportType;"windows-uwp"===a&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a||"windows-webview2"===a?window.open(b,"_blank"):this.Qg||(2===c?window.top.location=b:1===c?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,c=a.tag,"windows-uwp"===a.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,c))}],
["request-fullscreen",a=>{{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{document.exitFullscreen?
document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{t(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{t(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{t(this,"hashchange",{location:location.toString()})});
document.addEventListener("backbutton",()=>{t(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",a=>{a.handled=!0;t(this,"backbutton")})}Ac(f){alert(f.message)}Gc(f){f=f.isFocus;if("nwjs"===this.B){const a="nwjs"===this.B?nw.Window.get():null;f?a.focus():a.blur()}else f?window.focus():window.blur()}});"use strict";
{let f=!1;self.ua.Ca(class extends self.Da{constructor(a){super(a,"advert");a=b=>[b,c=>this.Xe(b,c)];H(this,[a("CreateBannerAdvert"),a("ShowBannerAdvert"),a("HideBannerAdvert"),a("CreateInterstitialAdvert"),a("ShowInterstitialAdvert"),a("CreateVideoAdvert"),a("ShowVideoAdvert"),a("Configure"),a("RequestConsent"),a("SetUserPersonalisation"),a("SetMaxAdContentRating"),a("TagForChildDirectedTreatment"),a("TagForUnderAgeOfConsent"),a("RequestIDFA")])}kf(){if(window.cordova)return window.cordova.plugins.ConstructAd}async Xe(a,
b){const c=this.kf();if(!c)throw f||(f=!0,console.warn("The Mobile Advert plugin is not loaded. Please note that it only works in Android or iOS exports")),Error("advert plugin not loaded");return new Promise((g,m)=>{c[a](...b,(p,v)=>{p?m(p):g(v)})})}})};
